name: Update flake inputs

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  schedule:
    # Monday updates gang
    - cron: '0 0 * * 1'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            nix flake update --commit-lock-file
          COMMIT_MESSAGE: 'build(flake): update inputs'
          PR_TITLE: 'build(flake): update inputs'
          PR_BRANCH_NAME: 'update/flake'
          GITHUB_TOKEN: ${{ secrets.FEMBOT_TOKEN }}
